language: java
jdk: oraclejdk8
sudo: false
script: mvn test
notifications:
  email:
    recipients:
      - deyneko55@gmsil.com
    on_success: never
    on_failure: always
notifications:
  slack: cbs-java:uZrfodvcQ0j2v9bcAncj3NNU